version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
      resource_class: large
    steps:
      - run : sudo apt-get -y update && sudo apt-get -y install curl python2 python3 python3-pip tzdata build-essential bc bison flex gcc clang libc6 libstdc++6 libssl-dev zip p7zip-full git
      - run : git clone https://github.com/Rmx1921/ci_script -b wip
      - run : cd ci_script
      - run : git clone https://github.com/Rmx1921/Anykernel
      - run : git clone https://github.com/Rmx1921/kernel_realme_sdm710.git
      #- run : git clone https://github.com/kdrag0n/proton-clang --depth=1
      - run : pwd
      - run : ls
      - run : bash ci_build.sh
