version: 2.1
jobs:
  compile:
   docker:
      - image: cimg/base:stable
   steps:
      - run:
          no_output_timeout: 50m 
          command: 
           apt-get -y update && apt-get -y upgrade && apt-get -y install python python2 python3 python3-pip tzdata build-essential bc bison flex gcc clang libc6 libstdc++6 libssl-dev zip p7zip-full git
           git clone https://github.com/Rmx1921/ci_script -b master
           cd ci_script
           git clone https://github.com/Rmx1921/Anykernel
           git clone https://github.com/Rmx1921/spiral_sdm710.git
           git clone https://github.com/kdrag0n/proton-clang.git --depth=1
           pip3 install -r requirements.txt   
           python3 ci_build.py --build --tele-notifier --tele-check --verbose --tele-tz Asia/Jakarta
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile