version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          no_output_timeout: 50m 
          command: |
           apt-get update && DEBIAN_FRONTEND="noninteractive" TZ="America/New_York" apt-get install -y tzdata
           apt-get -y update && apt-get -y upgrade && apt-get -y install python curl python python3 python3-pip tzdata build-essential bc bison flex gcc clang libc6 libstdc++6 libssl-dev zip p7zip-full git
           git clone https://github.com/Rmx1921/ci_script -b wip
           cd ci_script
           git clone https://github.com/Rmx1921/Anykernel
           git clone https://github.com/Rmx1921/kernel_realme_sdm710.git
           git clone https://github.com/kdrag0n/proton-clang --depth=1
   
           bash ci_build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
